insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Zero to Alpha: Return of the Wolf King', 'zero-to-alpha-return-of-the-wolf-king', 'Official short drama: Zero to Alpha: Return of the Wolf King', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/204200150000005685/36129862-e015-4070-a2be-9d41bd3ece5d.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', true, array['romance'] where not exists (select 1 from public.dramas where slug = 'zero-to-alpha-return-of-the-wolf-king' or title = 'Zero to Alpha: Return of the Wolf King');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'My X-Ray Vision Sees Right Through You', 'my-x-ray-vision-sees-right-through-you', 'Official short drama: My X-Ray Vision Sees Right Through You', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000000478/0348b57b-c85f-40e4-8e5f-2863a93ea786.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', true, array['romance'] where not exists (select 1 from public.dramas where slug = 'my-x-ray-vision-sees-right-through-you' or title = 'My X-Ray Vision Sees Right Through You');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'The Valkyrie Divorces the God of War', 'the-valkyrie-divorces-the-god-of-war', 'Official short drama: The Valkyrie Divorces the God of War', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/204200150000005667/e5eaf54a-96d2-440a-a3ff-1b651b6239fb.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', true, array['romance'] where not exists (select 1 from public.dramas where slug = 'the-valkyrie-divorces-the-god-of-war' or title = 'The Valkyrie Divorces the God of War');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Faking It with My Ex''s Best Friend', 'faking-it-with-my-ex-s-best-friend', 'Official short drama: Faking It with My Ex''s Best Friend', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000002139/da0f8d41-276b-445c-96fb-2887362e7242.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', true, array['romance'] where not exists (select 1 from public.dramas where slug = 'faking-it-with-my-ex-s-best-friend' or title = 'Faking It with My Ex''s Best Friend');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Brides in Smoke', 'brides-in-smoke', 'Official short drama: Brides in Smoke', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/204200150000005406/b4f87484-693d-44c4-9b78-afeeec53a252.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', true, array['romance'] where not exists (select 1 from public.dramas where slug = 'brides-in-smoke' or title = 'Brides in Smoke');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Sweet Temptation', 'sweet-temptation', 'Official short drama: Sweet Temptation', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000000382/a41e1ec5-887f-4a4e-8b0d-8aa063ddcf96.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', true, array['romance'] where not exists (select 1 from public.dramas where slug = 'sweet-temptation' or title = 'Sweet Temptation');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'The Fake Dating Spell', 'the-fake-dating-spell', 'Official short drama: The Fake Dating Spell', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/204200150000005757/05bd8293-e76d-4f0f-9ea2-4e5400f61c0e.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', true, array['romance'] where not exists (select 1 from public.dramas where slug = 'the-fake-dating-spell' or title = 'The Fake Dating Spell');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'A Ruler in Disguise', 'a-ruler-in-disguise', 'Official short drama: A Ruler in Disguise', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000005660/791356ef-d0fe-4408-85a6-f18dbc1c26e2.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', true, array['romance'] where not exists (select 1 from public.dramas where slug = 'a-ruler-in-disguise' or title = 'A Ruler in Disguise');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Keeping the Cowboy''s Baby', 'keeping-the-cowboy-s-baby', 'Official short drama: Keeping the Cowboy''s Baby', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000005763/23e0b459-b324-46cb-addf-700aaf6fef01.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'keeping-the-cowboy-s-baby' or title = 'Keeping the Cowboy''s Baby');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'My Firefighter Ex-Husband Burns in Regret', 'my-firefighter-ex-husband-burns-in-regret', 'Official short drama: My Firefighter Ex-Husband Burns in Regret', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000000123/716274d7-a079-44e2-851e-6f67b42379b3.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'my-firefighter-ex-husband-burns-in-regret' or title = 'My Firefighter Ex-Husband Burns in Regret');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'I''ll Make Your Daddy Mine', 'i-ll-make-your-daddy-mine', 'Official short drama: I''ll Make Your Daddy Mine', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000002992/493dbacb-8ac4-48ca-adf4-2677c3f82684.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'i-ll-make-your-daddy-mine' or title = 'I''ll Make Your Daddy Mine');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Nothing Escapes My Eyes', 'nothing-escapes-my-eyes', 'Official short drama: Nothing Escapes My Eyes', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000004758/30ecdaf8-80f6-4b62-a29a-69b699aa3316.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'nothing-escapes-my-eyes' or title = 'Nothing Escapes My Eyes');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Her Billionaire Father Spoils Her Rotten', 'her-billionaire-father-spoils-her-rotten', 'Official short drama: Her Billionaire Father Spoils Her Rotten', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000005417/e1e1d56c-16e5-4193-b988-eb04e2d321f7.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'her-billionaire-father-spoils-her-rotten' or title = 'Her Billionaire Father Spoils Her Rotten');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'American Sniper: The Kid of Guns', 'american-sniper-the-kid-of-guns', 'Official short drama: American Sniper: The Kid of Guns', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000004934/d837be5d-7c2e-4d86-b938-9150cff1ffb6.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'american-sniper-the-kid-of-guns' or title = 'American Sniper: The Kid of Guns');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Death Touch', 'death-touch', 'Official short drama: Death Touch', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000005358/f6513e47-a758-4945-8c22-b1b5f9cbb101.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'death-touch' or title = 'Death Touch');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'The Boss Affair', 'the-boss-affair', 'Official short drama: The Boss Affair', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000000004/99dfe613-2718-406d-b789-e0fffb42ca2d.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'the-boss-affair' or title = 'The Boss Affair');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Big Bad Husband, Please Wake Up!', 'big-bad-husband-please-wake-up', 'Official short drama: Big Bad Husband, Please Wake Up!', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000000005/a8b43d55-0785-432e-9167-8e4f50e29137.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'big-bad-husband-please-wake-up' or title = 'Big Bad Husband, Please Wake Up!');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Never Divorce a Secret Billionaire Heiress', 'never-divorce-a-secret-billionaire-heiress', 'Official short drama: Never Divorce a Secret Billionaire Heiress', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000000008/308af9b2-f3e8-42f9-ae93-5af83fde5ce3.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'never-divorce-a-secret-billionaire-heiress' or title = 'Never Divorce a Secret Billionaire Heiress');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Fated to My Forbidden Alpha', 'fated-to-my-forbidden-alpha', 'Official short drama: Fated to My Forbidden Alpha', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000000011/b8f0a9b5-b044-4e69-8ef9-407a0a7c7218.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'fated-to-my-forbidden-alpha' or title = 'Fated to My Forbidden Alpha');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'The Double Life of My Billionaire Husband', 'the-double-life-of-my-billionaire-husband', 'Official short drama: The Double Life of My Billionaire Husband', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000000045/e8922dfe-037f-4b51-bf03-edeb01ec74a9.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'the-double-life-of-my-billionaire-husband' or title = 'The Double Life of My Billionaire Husband');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Fatal Temptation: Between Two Alphas', 'fatal-temptation-between-two-alphas', 'Official short drama: Fatal Temptation: Between Two Alphas', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000000015/5ed04b28-8639-4698-b888-6b9f6626dbfd.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'fatal-temptation-between-two-alphas' or title = 'Fatal Temptation: Between Two Alphas');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Fatal Attraction: The Hybrid Princess', 'fatal-attraction-the-hybrid-princess', 'Official short drama: Fatal Attraction: The Hybrid Princess', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000000029/65caa0b7-b995-49c5-b5b6-97b7c54fcea3.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'fatal-attraction-the-hybrid-princess' or title = 'Fatal Attraction: The Hybrid Princess');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'True Luna', 'true-luna', 'Official short drama: True Luna', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000000025/82aa9fef-863c-4ec7-a323-46c9df919d91.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'true-luna' or title = 'True Luna');
insert into public.dramas (title, slug, synopsis, cover_url, status, is_trending, tags) select 'Married at First Sight', 'married-at-first-sight', 'Official short drama: Married at First Sight', 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/200000000000000034/515a843a-e1e8-4958-9567-42dfae048b26.jpg?x-oss-process=image/resize,w_640/quality,q_80', 'published', false, array['romance'] where not exists (select 1 from public.dramas where slug = 'married-at-first-sight' or title = 'Married at First Sight');
update public.dramas set cover_url = 'https://v-img.crazymaplestudios.com/v-images/book_cover_batch/204200150000005685/36129862-e015-4070-a2be-9d41bd3ece5d.jpg?x-oss-process=image/resize,w_640/quality,q_80' where title = 'Zero to Alpha: Return of the Wolf King';
update public.banners set image_url = 'https://v-mps.crazymaplestudios.com/images/63c4fb00-8987-11f1-8fc1-67160e4754e3.jpg' where title = 'Zero to Alpha: Return of the Wolf King';
update public.banners set image_url = 'https://v-mps.crazymaplestudios.com/images/1525ed20-7f59-11f1-8fc1-67160e4754e3.jpg' where title = 'The Boss Affair';
update public.banners set image_url = 'https://v-mps.crazymaplestudios.com/images/8340d350-8987-11f1-8fc1-67160e4754e3.jpg' where title = 'Fated to My Forbidden Alpha';
with ranked as (
  select id, row_number() over (order by updated_at desc) as rn
  from public.dramas where status = 'published'
)
insert into public.home_section_items (section_id, drama_id, sort_order)
select '1ef990da-c420-4880-8a20-b4cd0f86b955', r.id, r.rn
from ranked r
where r.rn <= 16
  and not exists (
    select 1 from public.home_section_items h
    where h.section_id = '1ef990da-c420-4880-8a20-b4cd0f86b955' and h.drama_id = r.id
  );

with ranked as (
  select id, row_number() over (order by is_trending desc, updated_at desc) as rn
  from public.dramas where status = 'published'
)
insert into public.home_section_items (section_id, drama_id, sort_order)
select 'f21c1913-c102-491d-b60b-f615677f56f8', r.id, r.rn
from ranked r
where r.rn <= 12
  and not exists (
    select 1 from public.home_section_items h
    where h.section_id = 'f21c1913-c102-491d-b60b-f615677f56f8' and h.drama_id = r.id
  );
